package cuevadelmonstruo;

/**
 *
 * @author gianm
 */
public class CuevaDelMonstruo extends javax.swing.JFrame {

	Cueva cueva;

	public CuevaDelMonstruo() {
		initComponents();
		cueva = new Cueva();
		cueva.agregarMonstruo(2, 2);
		cueva.agregarTesoro(5, 5);
		cueva.agregarPrecipicio(3, 3);
		cueva.agregarPrecipicio(3, 4);
		cueva.agregarMonstruo(3, 4);
		this.setSize(cueva.getPreferredSize());
		getContentPane().add(cueva);
		revalidate();
		repaint();
		this.pack();
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoConfiguracion = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tamCueva = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        filaTesoro = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        columnaTesoro = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filaMonstruo = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        columnaMonstruo = new javax.swing.JSpinner();
        botonMonstruo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filaPrecipicio = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        columnaPrecipicio = new javax.swing.JSpinner();
        botonPrecipicio = new javax.swing.JButton();
        botonTerminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        botonTamCueva = new javax.swing.JButton();
        botonTesoro = new javax.swing.JButton();
        botonReiniciar = new javax.swing.JButton();
        botonAvanzar = new javax.swing.JButton();
        principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuReiniciar = new javax.swing.JMenuItem();
        menuAvanzar = new javax.swing.JMenuItem();

        dialogoConfiguracion.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogoConfiguracion.setTitle("Configuración");
        dialogoConfiguracion.setAlwaysOnTop(true);
        dialogoConfiguracion.setSize(new java.awt.Dimension(494, 246));
        dialogoConfiguracion.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogoConfiguracionWindowClosed(evt);
            }
        });

        jLabel1.setText("¿En qué posición debe estar el tesoro?");

        jLabel2.setText("¿Qué tamaño debe tener la cueva? Elige n, la cueva es de nxn:");

        tamCueva.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));
        tamCueva.setName("tamCuevaSpinner"); // NOI18N

        jLabel3.setText("Fila:");

        filaTesoro.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));

        jLabel4.setText("Columna:");

        columnaTesoro.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));

        jLabel5.setText("Poner un monstruo en esta posición:");

        jLabel6.setText("Fila:");

        filaMonstruo.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));

        jLabel7.setText("Columna:");

        columnaMonstruo.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));

        botonMonstruo.setText("Confirmar");
        botonMonstruo.setEnabled(false);
        botonMonstruo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMonstruoActionPerformed(evt);
            }
        });

        jLabel8.setText("Poner un precipicio en esta posición:");

        jLabel9.setText("Fila:");

        filaPrecipicio.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));

        jLabel10.setText("Columna:");

        columnaPrecipicio.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));

        botonPrecipicio.setText("Confirmar");
        botonPrecipicio.setEnabled(false);
        botonPrecipicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrecipicioActionPerformed(evt);
            }
        });

        botonTerminar.setText("Terminar");
        botonTerminar.setEnabled(false);
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });

        jLabel11.setText("Solo se pondrán monstruos o precipicios en zonas permitidas");

        botonTamCueva.setText("Confirmar");
        botonTamCueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTamCuevaMouseClicked(evt);
            }
        });
        botonTamCueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTamCuevaActionPerformed(evt);
            }
        });

        botonTesoro.setText("Confirmar");
        botonTesoro.setEnabled(false);
        botonTesoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTesoroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoConfiguracionLayout = new javax.swing.GroupLayout(dialogoConfiguracion.getContentPane());
        dialogoConfiguracion.getContentPane().setLayout(dialogoConfiguracionLayout);
        dialogoConfiguracionLayout.setHorizontalGroup(
            dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoConfiguracionLayout.createSequentialGroup()
                        .addGroup(dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dialogoConfiguracionLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tamCueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoConfiguracionLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filaMonstruo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(columnaMonstruo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoConfiguracionLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filaPrecipicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(10, 10, 10)
                                .addComponent(columnaPrecipicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoConfiguracionLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(filaTesoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(columnaTesoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonMonstruo)
                                .addComponent(botonPrecipicio)
                                .addComponent(botonTamCueva, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(botonTesoro, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoConfiguracionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonTerminar)
                .addGap(206, 206, 206))
        );
        dialogoConfiguracionLayout.setVerticalGroup(
            dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoConfiguracionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tamCueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTamCueva))
                .addGap(18, 18, 18)
                .addGroup(dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(filaTesoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(columnaTesoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTesoro))
                .addGap(18, 18, 18)
                .addGroup(dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(filaMonstruo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(columnaMonstruo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMonstruo))
                .addGap(18, 18, 18)
                .addGroup(dialogoConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(filaPrecipicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(columnaPrecipicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPrecipicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonTerminar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cueva del monstruo");
        setBackground(new java.awt.Color(153, 153, 153));
        setName("Ventana principal"); // NOI18N

        botonReiniciar.setText("Reiniciar");
        botonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarActionPerformed(evt);
            }
        });

        botonAvanzar.setText("Avanzar");
        botonAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAvanzarActionPerformed(evt);
            }
        });

        principal.setBackground(new java.awt.Color(255, 51, 51));
        principal.setName("principal"); // NOI18N
        principal.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("Opciones");

        menuReiniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        menuReiniciar.setText("Reiniciar");
        menuReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReiniciarActionPerformed(evt);
            }
        });
        jMenu1.add(menuReiniciar);

        menuAvanzar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.CTRL_MASK));
        menuAvanzar.setText("Avanzar");
        menuAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAvanzarActionPerformed(evt);
            }
        });
        jMenu1.add(menuAvanzar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAvanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAvanzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReiniciarActionPerformed
		dialogoConfiguracion.pack();
		dialogoConfiguracion.setLocationRelativeTo(null);
		dialogoConfiguracion.setVisible(true);
		botonTamCueva.setEnabled(true);
		botonTesoro.setEnabled(false);
		botonMonstruo.setEnabled(false);
		botonPrecipicio.setEnabled(false);
		botonTerminar.setEnabled(false);
    }//GEN-LAST:event_menuReiniciarActionPerformed

    private void menuAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAvanzarActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_menuAvanzarActionPerformed

    private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarActionPerformed
		dialogoConfiguracion.pack();
		dialogoConfiguracion.setLocationRelativeTo(null);
		dialogoConfiguracion.setVisible(true);
		botonTamCueva.setEnabled(true);
		botonTesoro.setEnabled(false);
		botonMonstruo.setEnabled(false);
		botonPrecipicio.setEnabled(false);
		botonTerminar.setEnabled(false);
    }//GEN-LAST:event_botonReiniciarActionPerformed

    private void botonAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAvanzarActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_botonAvanzarActionPerformed

    private void botonTamCuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTamCuevaMouseClicked
		// TODO add your handling code here:

    }//GEN-LAST:event_botonTamCuevaMouseClicked

    private void botonTamCuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTamCuevaActionPerformed
		cueva=new Cueva();
		javax.swing.JButton source = (javax.swing.JButton) evt.getSource();
		source.setEnabled(false);
		// Activar el resto de botones
		botonTesoro.setEnabled(true);
		botonMonstruo.setEnabled(true);
		botonPrecipicio.setEnabled(true);
    }//GEN-LAST:event_botonTamCuevaActionPerformed

    private void botonTesoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTesoroActionPerformed
		int fila = (Integer) filaTesoro.getValue();
		int columna = (Integer) columnaTesoro.getValue();
		if (fila == 1 && columna == 1) {
			return;
		}
		if (cueva.agregarTesoro(fila, columna)) {
			javax.swing.JButton source = (javax.swing.JButton) evt.getSource();
			source.setEnabled(false);
			botonTerminar.setEnabled(true);
		}
    }//GEN-LAST:event_botonTesoroActionPerformed

    private void dialogoConfiguracionWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogoConfiguracionWindowClosed
		// TODO add your handling code here:
    }//GEN-LAST:event_dialogoConfiguracionWindowClosed

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
		dialogoConfiguracion.dispose();
		dialogoConfiguracion.setVisible(false);
		this.add(cueva);
		this.revalidate();
		this.pack();
		this.setVisible(true);
    }//GEN-LAST:event_botonTerminarActionPerformed

    private void botonMonstruoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMonstruoActionPerformed
		int fila = (Integer) filaMonstruo.getValue();
		int columna = (Integer) columnaMonstruo.getValue();
		cueva.agregarMonstruo(fila, columna);
    }//GEN-LAST:event_botonMonstruoActionPerformed

    private void botonPrecipicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrecipicioActionPerformed
		int fila = (Integer) filaPrecipicio.getValue();
		int columna = (Integer) columnaPrecipicio.getValue();
		cueva.agregarPrecipicio(fila, columna);
    }//GEN-LAST:event_botonPrecipicioActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CuevaDelMonstruo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CuevaDelMonstruo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CuevaDelMonstruo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CuevaDelMonstruo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				CuevaDelMonstruo cuevaMonstruo = new CuevaDelMonstruo();
				cuevaMonstruo.setLocationRelativeTo(null);
				cuevaMonstruo.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAvanzar;
    private javax.swing.JButton botonMonstruo;
    private javax.swing.JButton botonPrecipicio;
    private javax.swing.JButton botonReiniciar;
    private javax.swing.JButton botonTamCueva;
    private javax.swing.JButton botonTerminar;
    private javax.swing.JButton botonTesoro;
    private javax.swing.JSpinner columnaMonstruo;
    private javax.swing.JSpinner columnaPrecipicio;
    private javax.swing.JSpinner columnaTesoro;
    private javax.swing.JDialog dialogoConfiguracion;
    private javax.swing.JSpinner filaMonstruo;
    private javax.swing.JSpinner filaPrecipicio;
    private javax.swing.JSpinner filaTesoro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAvanzar;
    private javax.swing.JMenuItem menuReiniciar;
    private javax.swing.JPanel principal;
    private javax.swing.JSpinner tamCueva;
    // End of variables declaration//GEN-END:variables
}
